name = "ExpressDB"
uuid = "18b0655d-4a43-4d76-9339-669ee99a06f5"
authors = ["singularitti <singularitti@outlook.com> and contributors"]
version = "0.1.0"

[deps]
ChemicalFormula = "069161ab-964a-4228-89a0-7a676f2e1f46"
CrystallographyBase = "93b1d1cd-a8ea-4aa5-adb1-b2407ea0ba8d"
ExpressBase = "6bf22d12-b2e3-4e51-8f6d-9d050a32c5d5"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"

[compat]
ChemicalFormula = "0.1"
ExpressBase = "0.4"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
